### ISSUE TITLE
attempt to index upvalue 'dvd' (a nil value)

### ISSUE THREAD

**Issue by zephyrus92** [CogentRedTester/mpv-dvd-browser#3]
When I launch mpv using `mpv dvd://`, I receive this output pertaining to the dvd browser plugin:

```
[dvd_browser]
[dvd_browser] stack traceback:
[dvd_browser]   mp.defaults:600: in function 'handler'
[dvd_browser]   mp.defaults:510: in function 'call_event_handlers'
[dvd_browser]   mp.defaults:555: in function 'dispatch_events'
[dvd_browser]   mp.defaults:503: in function <mp.defaults:502>
[dvd_browser]   [C]: at 0x56312ed7a180
[dvd_browser]   [C]: at 0x56312ed7a7f0
[dvd_browser] Lua error: [string "/home/user/.config/mpv/scripts/dvd-browser.lua"]:367: attempt to index upvalue 'dvd' (a nil value)
client removed during hook handling
```

`scroll-list.lua` is located at `~~/script-modules` and seems to be working fine. I wasn't sure where to put `dvd_browser.conf` though and ended up putting it in `.config/mpv/script-opts`.

I have installed lsdvd and do have a symlink in `/dev` for the dvd  device that is pointing to `/dev/sr0`.

Any idea what could be the issue?

**Comment by CogentRedTester** [comment]
Please upload a full log file of the error using the `--log-file` and `--msg-level=dvd_browser='trace'` options.

**Comment by CogentRedTester** [comment]
Closing as I never received a log.
