### ISSUE TITLE
MPV closes in the last chapter

### ISSUE THREAD

**Issue by Meowsod** [CogentRedTester/mpv-dvd-browser#4]
MPV closes in the last chapter

```AV: 00:46:02 / 01:09:05 (67%) A-V:  0.000
[disc] PTS discontinuity: 1381.257722->0.144656
[disc] PTS discontinuity: 0.178022->1381.266022
AV: 00:46:02 / 01:09:05 (67%) A-V:  0.000
[disc] PTS discontinuity: 1381.266022->0.178022
AV: 00:46:04 / 01:09:05 (67%) A-V:  0.000

Exiting... (End of file)
[dvd_browser] Exiting...```

**Comment by CogentRedTester** [comment]
Can you provide a few more details? I assume this is due to the `escape_loop` feature which prevents some DVDs from entering an infinite loop in the last chapter. Setting `escape_loop=no` in `dvd_browser.conf` would disable the feature.

**Comment by Meowsod** [comment]
That fixed the issue, thanks!

**Comment by CogentRedTester** [comment]
Can you give me the name of the DVD that you're testing this on and the track that you're playing? All of my DVDs have that infinite loop chapter, but I'd like to know about others that are different.

**Comment by Meowsod** [comment]
Didn't use it to play back physical DVDs, if I recall correctly it happened on all the last chapters of the ISOs I tried.
mpv dvd:// --dvd-device=dvdvolume.iso
Here's one set of discs which I used it on https://archive.org/details/alfred-j-kwak-dvd

**Comment by Meowsod** [comment]
Having this error on one set of discs on the updated version
```[dvd_browser] 
[dvd_browser] stack traceback:
[dvd_browser] 	[string "/home/hifovop/.config/mpv/scripts/dvd-browser..."]:365: in function 'fn'
[dvd_browser] 	mp.defaults:579: in function 'handler'
[dvd_browser] 	mp.defaults:500: in function 'call_event_handlers'
[dvd_browser] 	mp.defaults:534: in function 'dispatch_events'
[dvd_browser] 	mp.defaults:493: in function <mp.defaults:492>
[dvd_browser] 	[C]: in ?
[dvd_browser] 	[C]: in ?
[dvd_browser] Lua error: [string "/home/hifovop/.config/mpv/scripts/dvd-browser..."]:365: attempt to index field '?' (a nil value)
client removed during hook handling```

**Comment by CogentRedTester** [comment]
Can you please copy the updated script from [here](https://github.com/CogentRedTester/mpv-dvd-browser/blob/issue4-debug/dvd-browser.lua) and send me the debug message that comes up. it should say `DEBUG_MESSAGE: ...`.

**Comment by Meowsod** [comment]
[dvd_browser] DEBUG_MESSAGE: 0   {}  
[dvd_browser] 
[dvd_browser] stack traceback:
[dvd_browser] 	[string "/home/hifovop/.config/mpv/scripts/dvd-browser..."]:364: in function 'fn'
[dvd_browser] 	mp.defaults:579: in function 'handler'
[dvd_browser] 	mp.defaults:500: in function 'call_event_handlers'
[dvd_browser] 	mp.defaults:534: in function 'dispatch_events'
[dvd_browser] 	mp.defaults:493: in function <mp.defaults:492>
[dvd_browser] 	[C]: in ?
[dvd_browser] 	[C]: in ?

**Comment by CogentRedTester** [comment]
Did you cut out the `Lua error` part of the error message?

**Comment by Meowsod** [comment]
oops, sorry
[dvd_browser] DEBUG_MESSAGE: 0   {} 
[dvd_browser] 
[dvd_browser] stack traceback:
[dvd_browser] 	[string "/home/hifovop/.config/mpv/scripts/dvd-browser..."]:364: in function 'fn'
[dvd_browser] 	mp.defaults:579: in function 'handler'
[dvd_browser] 	mp.defaults:500: in function 'call_event_handlers'
[dvd_browser] 	mp.defaults:534: in function 'dispatch_events'
[dvd_browser] 	mp.defaults:493: in function <mp.defaults:492>
[dvd_browser] 	[C]: in ?
[dvd_browser] 	[C]: in ?
[dvd_browser] Lua error: [string "/home/hifovop/.config/mpv/scripts/dvd-browser..."]:364: attempt to index field '?' (a nil value)

**Comment by CogentRedTester** [comment]
Ok some very weird stuff is happening. I've added another debug statement if you could download it from the same link and run it again.

**Comment by Meowsod** [comment]
[dvd_browser] DEBUG_MESSAGE: table: 0x7f6d7805e2c0 table 
[dvd_browser] DEBUG_MESSAGE: 0   {} 
[dvd_browser] 
[dvd_browser] stack traceback:
[dvd_browser] 	[string "/home/hifovop/.config/mpv/scripts/dvd-browser..."]:367: in function 'fn'
[dvd_browser] 	mp.defaults:579: in function 'handler'
[dvd_browser] 	mp.defaults:500: in function 'call_event_handlers'
[dvd_browser] 	mp.defaults:534: in function 'dispatch_events'
[dvd_browser] 	mp.defaults:493: in function <mp.defaults:492>
[dvd_browser] 	[C]: in ?
[dvd_browser] 	[C]: in ?
[dvd_browser] Lua error: [string "/home/hifovop/.config/mpv/scripts/dvd-browser..."]:367: attempt to index field '?' (a nil value)

**Comment by CogentRedTester** [comment]
Ok I think I have figured it out. Download the latest version of the script from the master branch [here](https://github.com/CogentRedTester/mpv-dvd-browser/blob/master/dvd-browser.lua).

**Comment by Meowsod** [comment]
works now 👍
