### ISSUE TITLE
Error: Cannot find main.* for any supported scripting backend in: /home/userfolder/.config/mpv/scripts/dvd-browser

### ISSUE THREAD

**Issue by its-thomas** [CogentRedTester/mpv-dvd-browser#5]
Hi there,

I am very sorry to post this seemingly mondane issue, but I cannot get your script to work on my debian 12 machine (latest updates installed).

1. I have downloaded the zip and extracted the content to `/home/userfolder/.config/mpv/scripts/dvd-browser/` 
2. I have set `dvd_device=/dev/sr0` in the `dvd_browser.conf` file because my `lsdvd` commands needs to be pointed there (simply executing `lsdvd` in terminal returns "Can't find device /dev/dvd")
3. I have placed `scroll-list.lua` into the `/home/userfolder/.config/mpv/script-modules/` folder

Now when I start mpv via terminal, I get the following message in red:

_Cannot find main.* for any supported scripting backend in: /home/userfolder/.config/mpv/scripts/dvd-browser_

Any help is greatly appreciated.
Thomas

**Comment by its-thomas** [comment]
OK, through simple trial and error, I have found the following configuration to be working for me:

1. `/home/userfolder/.config/mpv/scripts/dvd-browser.lua`
2. `/home/userfolder/.config/mpv/script-opts/dvd_browser.conf` with `dvd_device=/dev/sr0` set
3. `/home/userfolder/.config/mpv/script-modules/scroll-list.lua`

No other files or folders exist within my `/home/userfolder/.config/mpv` folder.

The above mentioned error 

> Cannot find main.* for any supported scripting backend in: /home/userfolder/.config/mpv/scripts/dvd-browser

 is not shown anymore in the terminal and pressing the menu button during playback brings up the DVD content list as expected.

Thanks a lot for this very useful script!

Thomas

**Comment by CogentRedTester** [comment]
You can't have folders in the `~~/scripts` directory, if you do they are treated as directory scripts that require a `main.lua` file as the entrypoint:

> If a script is a directory (either if a directory is passed to --script, or any sub-directories in the script directory, such as for example ~/.config/mpv/scripts/something/), then the directory represents a single script. The player will try to load a file named main.x, where x is replaced with the file extension. For example, if main.lua exists, it is loaded with the Lua scripting backend.

[Source](https://mpv.io/manual/master/#script-location).
